name: restquester
description: Package simplifying rest requests. It is wrapping basic http requests providing additional functionality like mapping json to data model.
version: 0.5.4
homepage: https://stonks.pl

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: