name: restquester
description: Package simplifying rest requests
version: 0.5.0
author: Jakub Neukirch
homepage: stonks.pl

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: 0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: